window.WC_DATA = {
 "updated": "2026-07-08T02:09:57+08:00",
 "matches": [
  {
   "id": 1,
   "stage": "group",
   "group": "A",
   "date": "2026-06-12",
   "t": "09:00",
   "home": "MEX",
   "away": "RSA",
   "venue": "墨西哥城",
   "result": "H",
   "score": "2-0"
  },
  {
   "id": 2,
   "stage": "group",
   "group": "A",
   "date": "2026-06-12",
   "t": "10:00",
   "home": "KOR",
   "away": "CZE",
   "venue": "瓜达拉哈拉",
   "result": "H",
   "score": "2-1"
  },
  {
   "id": 3,
   "stage": "group",
   "group": "B",
   "date": "2026-06-13",
   "t": "03:00",
   "home": "CAN",
   "away": "BIH",
   "venue": "多伦多",
   "result": null,
   "score": null
  },
  {
   "id": 4,
   "stage": "group",
   "group": "D",
   "date": "2026-06-13",
   "t": "09:00",
   "home": "USA",
   "away": "PAR",
   "venue": "洛杉矶",
   "result": "H",
   "score": "4-1"
  },
  {
   "id": 5,
   "stage": "group",
   "group": "B",
   "date": "2026-06-14",
   "t": "03:00",
   "home": "QAT",
   "away": "SUI",
   "venue": "旧金山",
   "result": "D",
   "score": "1-1"
  },
  {
   "id": 6,
   "stage": "group",
   "group": "C",
   "date": "2026-06-14",
   "t": "06:00",
   "home": "BRA",
   "away": "MAR",
   "venue": "纽约/新泽西",
   "result": "D",
   "score": "1-1"
  },
  {
   "id": 7,
   "stage": "group",
   "group": "C",
   "date": "2026-06-14",
   "t": "09:00",
   "home": "HAI",
   "away": "SCO",
   "venue": "波士顿",
   "result": "A",
   "score": "0-1"
  },
  {
   "id": 8,
   "stage": "group",
   "group": "D",
   "date": "2026-06-14",
   "t": "12:00",
   "home": "AUS",
   "away": "TUR",
   "venue": "温哥华",
   "result": "H",
   "score": "2-0"
  },
  {
   "id": 9,
   "stage": "group",
   "group": "E",
   "date": "2026-06-15",
   "t": "01:00",
   "home": "GER",
   "away": "CUW",
   "venue": "休斯敦",
   "result": "H",
   "score": "7-1"
  },
  {
   "id": 10,
   "stage": "group",
   "group": "F",
   "date": "2026-06-15",
   "t": "04:00",
   "home": "NED",
   "away": "JPN",
   "venue": "达拉斯",
   "result": "D",
   "score": "2-2"
  },
  {
   "id": 11,
   "stage": "group",
   "group": "E",
   "date": "2026-06-15",
   "t": "07:00",
   "home": "CIV",
   "away": "ECU",
   "venue": "费城",
   "result": "H",
   "score": "1-0"
  },
  {
   "id": 12,
   "stage": "group",
   "group": "F",
   "date": "2026-06-15",
   "t": "10:00",
   "home": "SWE",
   "away": "TUN",
   "venue": "蒙特雷",
   "result": "H",
   "score": "5-1"
  },
  {
   "id": 13,
   "stage": "group",
   "group": "H",
   "date": "2026-06-16",
   "t": "01:00",
   "home": "ESP",
   "away": "CPV",
   "venue": "亚特兰大",
   "result": "D",
   "score": "0-0"
  },
  {
   "id": 14,
   "stage": "group",
   "group": "G",
   "date": "2026-06-16",
   "t": "06:00",
   "home": "BEL",
   "away": "EGY",
   "venue": "温哥华",
   "result": "D",
   "score": "1-1"
  },
  {
   "id": 15,
   "stage": "group",
   "group": "H",
   "date": "2026-06-16",
   "t": "06:00",
   "home": "KSA",
   "away": "URU",
   "venue": "迈阿密",
   "result": "D",
   "score": "1-1"
  },
  {
   "id": 16,
   "stage": "group",
   "group": "G",
   "date": "2026-06-16",
   "t": "12:00",
   "home": "IRN",
   "away": "NZL",
   "venue": "洛杉矶",
   "result": "D",
   "score": "2-2"
  },
  {
   "id": 17,
   "stage": "group",
   "group": "I",
   "date": "2026-06-17",
   "t": "03:00",
   "home": "FRA",
   "away": "SEN",
   "venue": "纽约/新泽西",
   "result": "H",
   "score": "3-1"
  },
  {
   "id": 18,
   "stage": "group",
   "group": "I",
   "date": "2026-06-17",
   "t": "06:00",
   "home": "IRQ",
   "away": "NOR",
   "venue": "波士顿",
   "result": "A",
   "score": "1-4"
  },
  {
   "id": 19,
   "stage": "group",
   "group": "J",
   "date": "2026-06-17",
   "t": "09:00",
   "home": "ARG",
   "away": "ALG",
   "venue": "堪萨斯城",
   "result": "H",
   "score": "3-0"
  },
  {
   "id": 20,
   "stage": "group",
   "group": "J",
   "date": "2026-06-17",
   "t": "12:00",
   "home": "AUT",
   "away": "JOR",
   "venue": "旧金山",
   "result": "H",
   "score": "3-1"
  },
  {
   "id": 21,
   "stage": "group",
   "group": "K",
   "date": "2026-06-18",
   "t": "01:00",
   "home": "POR",
   "away": "COD",
   "venue": "休斯敦",
   "result": "D",
   "score": "1-1"
  },
  {
   "id": 22,
   "stage": "group",
   "group": "L",
   "date": "2026-06-18",
   "t": "04:00",
   "home": "ENG",
   "away": "CRO",
   "venue": "达拉斯",
   "result": "H",
   "score": "4-2"
  },
  {
   "id": 23,
   "stage": "group",
   "group": "L",
   "date": "2026-06-18",
   "t": "07:00",
   "home": "GHA",
   "away": "PAN",
   "venue": "多伦多",
   "result": "H",
   "score": "1-0"
  },
  {
   "id": 24,
   "stage": "group",
   "group": "K",
   "date": "2026-06-18",
   "t": "10:00",
   "home": "UZB",
   "away": "COL",
   "venue": "墨西哥城",
   "result": "A",
   "score": "1-3"
  },
  {
   "id": 25,
   "stage": "group",
   "group": "A",
   "date": "2026-06-19",
   "t": "00:00",
   "home": "CZE",
   "away": "RSA",
   "venue": "亚特兰大",
   "result": "D",
   "score": "1-1"
  },
  {
   "id": 26,
   "stage": "group",
   "group": "B",
   "date": "2026-06-19",
   "t": "03:00",
   "home": "SUI",
   "away": "BIH",
   "venue": "洛杉矶",
   "result": null,
   "score": null
  },
  {
   "id": 27,
   "stage": "group",
   "group": "B",
   "date": "2026-06-19",
   "t": "06:00",
   "home": "CAN",
   "away": "QAT",
   "venue": "温哥华",
   "result": "H",
   "score": "6-0"
  },
  {
   "id": 28,
   "stage": "group",
   "group": "A",
   "date": "2026-06-19",
   "t": "11:00",
   "home": "MEX",
   "away": "KOR",
   "venue": "瓜达拉哈拉",
   "result": "H",
   "score": "1-0"
  },
  {
   "id": 29,
   "stage": "group",
   "group": "D",
   "date": "2026-06-20",
   "t": "03:00",
   "home": "USA",
   "away": "AUS",
   "venue": "西雅图",
   "result": "H",
   "score": "2-0"
  },
  {
   "id": 30,
   "stage": "group",
   "group": "C",
   "date": "2026-06-20",
   "t": "06:00",
   "home": "SCO",
   "away": "MAR",
   "venue": "波士顿",
   "result": "A",
   "score": "0-1"
  },
  {
   "id": 31,
   "stage": "group",
   "group": "C",
   "date": "2026-06-20",
   "t": "09:00",
   "home": "BRA",
   "away": "HAI",
   "venue": "费城",
   "result": "H",
   "score": "3-0"
  },
  {
   "id": 32,
   "stage": "group",
   "group": "D",
   "date": "2026-06-20",
   "t": "12:00",
   "home": "TUR",
   "away": "PAR",
   "venue": "旧金山",
   "result": "A",
   "score": "0-1"
  },
  {
   "id": 33,
   "stage": "group",
   "group": "F",
   "date": "2026-06-21",
   "t": "01:00",
   "home": "NED",
   "away": "SWE",
   "venue": "休斯敦",
   "result": "H",
   "score": "5-1"
  },
  {
   "id": 34,
   "stage": "group",
   "group": "E",
   "date": "2026-06-21",
   "t": "04:00",
   "home": "GER",
   "away": "CIV",
   "venue": "多伦多",
   "result": "H",
   "score": "2-1"
  },
  {
   "id": 35,
   "stage": "group",
   "group": "E",
   "date": "2026-06-21",
   "t": "08:00",
   "home": "ECU",
   "away": "CUW",
   "venue": "堪萨斯城",
   "result": "D",
   "score": "0-0"
  },
  {
   "id": 36,
   "stage": "group",
   "group": "F",
   "date": "2026-06-21",
   "t": "12:00",
   "home": "TUN",
   "away": "JPN",
   "venue": "蒙特雷",
   "result": "A",
   "score": "0-4"
  },
  {
   "id": 37,
   "stage": "group",
   "group": "H",
   "date": "2026-06-22",
   "t": "00:00",
   "home": "ESP",
   "away": "KSA",
   "venue": "亚特兰大",
   "result": "H",
   "score": "4-0"
  },
  {
   "id": 38,
   "stage": "group",
   "group": "G",
   "date": "2026-06-22",
   "t": "03:00",
   "home": "BEL",
   "away": "IRN",
   "venue": "洛杉矶",
   "result": "D",
   "score": "0-0"
  },
  {
   "id": 39,
   "stage": "group",
   "group": "H",
   "date": "2026-06-22",
   "t": "06:00",
   "home": "URU",
   "away": "CPV",
   "venue": "迈阿密",
   "result": "D",
   "score": "2-2"
  },
  {
   "id": 40,
   "stage": "group",
   "group": "G",
   "date": "2026-06-22",
   "t": "09:00",
   "home": "NZL",
   "away": "EGY",
   "venue": "温哥华",
   "result": "A",
   "score": "1-3"
  },
  {
   "id": 41,
   "stage": "group",
   "group": "J",
   "date": "2026-06-23",
   "t": "01:00",
   "home": "ARG",
   "away": "AUT",
   "venue": "达拉斯",
   "result": "H",
   "score": "2-0"
  },
  {
   "id": 42,
   "stage": "group",
   "group": "I",
   "date": "2026-06-23",
   "t": "05:00",
   "home": "FRA",
   "away": "IRQ",
   "venue": "费城",
   "result": "H",
   "score": "3-0"
  },
  {
   "id": 43,
   "stage": "group",
   "group": "I",
   "date": "2026-06-23",
   "t": "08:00",
   "home": "NOR",
   "away": "SEN",
   "venue": "纽约/新泽西",
   "result": "H",
   "score": "3-2"
  },
  {
   "id": 44,
   "stage": "group",
   "group": "J",
   "date": "2026-06-23",
   "t": "11:00",
   "home": "JOR",
   "away": "ALG",
   "venue": "旧金山",
   "result": "A",
   "score": "1-2"
  },
  {
   "id": 45,
   "stage": "group",
   "group": "K",
   "date": "2026-06-24",
   "t": "01:00",
   "home": "POR",
   "away": "UZB",
   "venue": "休斯敦",
   "result": "H",
   "score": "5-0"
  },
  {
   "id": 46,
   "stage": "group",
   "group": "L",
   "date": "2026-06-24",
   "t": "04:00",
   "home": "ENG",
   "away": "GHA",
   "venue": "波士顿",
   "result": "D",
   "score": "0-0"
  },
  {
   "id": 47,
   "stage": "group",
   "group": "L",
   "date": "2026-06-24",
   "t": "07:00",
   "home": "PAN",
   "away": "CRO",
   "venue": "多伦多",
   "result": "A",
   "score": "0-1"
  },
  {
   "id": 48,
   "stage": "group",
   "group": "K",
   "date": "2026-06-24",
   "t": "10:00",
   "home": "COL",
   "away": "COD",
   "venue": "瓜达拉哈拉",
   "result": "H",
   "score": "1-0"
  },
  {
   "id": 49,
   "stage": "group",
   "group": "B",
   "date": "2026-06-25",
   "t": "03:00",
   "home": "SUI",
   "away": "CAN",
   "venue": "温哥华",
   "result": "H",
   "score": "2-1"
  },
  {
   "id": 50,
   "stage": "group",
   "group": "B",
   "date": "2026-06-25",
   "t": "03:00",
   "home": "BIH",
   "away": "QAT",
   "venue": "西雅图",
   "result": null,
   "score": null
  },
  {
   "id": 51,
   "stage": "group",
   "group": "C",
   "date": "2026-06-25",
   "t": "06:00",
   "home": "SCO",
   "away": "BRA",
   "venue": "迈阿密",
   "result": "A",
   "score": "0-3"
  },
  {
   "id": 52,
   "stage": "group",
   "group": "C",
   "date": "2026-06-25",
   "t": "06:00",
   "home": "MAR",
   "away": "HAI",
   "venue": "亚特兰大",
   "result": "H",
   "score": "4-2"
  },
  {
   "id": 53,
   "stage": "group",
   "group": "A",
   "date": "2026-06-25",
   "t": "09:00",
   "home": "CZE",
   "away": "MEX",
   "venue": "墨西哥城",
   "result": "A",
   "score": "0-3"
  },
  {
   "id": 54,
   "stage": "group",
   "group": "A",
   "date": "2026-06-25",
   "t": "09:00",
   "home": "RSA",
   "away": "KOR",
   "venue": "蒙特雷",
   "result": "H",
   "score": "1-0"
  },
  {
   "id": 55,
   "stage": "group",
   "group": "E",
   "date": "2026-06-26",
   "t": "04:00",
   "home": "ECU",
   "away": "GER",
   "venue": "纽约/新泽西",
   "result": "H",
   "score": "2-1"
  },
  {
   "id": 56,
   "stage": "group",
   "group": "E",
   "date": "2026-06-26",
   "t": "04:00",
   "home": "CUW",
   "away": "CIV",
   "venue": "费城",
   "result": "A",
   "score": "0-2"
  },
  {
   "id": 57,
   "stage": "group",
   "group": "F",
   "date": "2026-06-26",
   "t": "07:00",
   "home": "JPN",
   "away": "SWE",
   "venue": "达拉斯",
   "result": "D",
   "score": "1-1"
  },
  {
   "id": 58,
   "stage": "group",
   "group": "F",
   "date": "2026-06-26",
   "t": "07:00",
   "home": "TUN",
   "away": "NED",
   "venue": "堪萨斯城",
   "result": "A",
   "score": "1-3"
  },
  {
   "id": 59,
   "stage": "group",
   "group": "D",
   "date": "2026-06-26",
   "t": "10:00",
   "home": "TUR",
   "away": "USA",
   "venue": "洛杉矶",
   "result": "H",
   "score": "3-2"
  },
  {
   "id": 60,
   "stage": "group",
   "group": "D",
   "date": "2026-06-26",
   "t": "10:00",
   "home": "PAR",
   "away": "AUS",
   "venue": "旧金山",
   "result": "D",
   "score": "0-0"
  },
  {
   "id": 61,
   "stage": "group",
   "group": "I",
   "date": "2026-06-27",
   "t": "03:00",
   "home": "NOR",
   "away": "FRA",
   "venue": "波士顿",
   "result": "A",
   "score": "1-4"
  },
  {
   "id": 62,
   "stage": "group",
   "group": "I",
   "date": "2026-06-27",
   "t": "03:00",
   "home": "SEN",
   "away": "IRQ",
   "venue": "多伦多",
   "result": "H",
   "score": "5-0"
  },
  {
   "id": 63,
   "stage": "group",
   "group": "H",
   "date": "2026-06-27",
   "t": "08:00",
   "home": "CPV",
   "away": "KSA",
   "venue": "休斯敦",
   "result": "D",
   "score": "0-0"
  },
  {
   "id": 64,
   "stage": "group",
   "group": "H",
   "date": "2026-06-27",
   "t": "08:00",
   "home": "URU",
   "away": "ESP",
   "venue": "瓜达拉哈拉",
   "result": "A",
   "score": "0-1"
  },
  {
   "id": 65,
   "stage": "group",
   "group": "G",
   "date": "2026-06-27",
   "t": "11:00",
   "home": "EGY",
   "away": "IRN",
   "venue": "西雅图",
   "result": "D",
   "score": "1-1"
  },
  {
   "id": 66,
   "stage": "group",
   "group": "G",
   "date": "2026-06-27",
   "t": "11:00",
   "home": "NZL",
   "away": "BEL",
   "venue": "温哥华",
   "result": "A",
   "score": "1-5"
  },
  {
   "id": 67,
   "stage": "group",
   "group": "L",
   "date": "2026-06-28",
   "t": "05:00",
   "home": "PAN",
   "away": "ENG",
   "venue": "纽约/新泽西",
   "result": "A",
   "score": "0-2"
  },
  {
   "id": 68,
   "stage": "group",
   "group": "L",
   "date": "2026-06-28",
   "t": "05:00",
   "home": "CRO",
   "away": "GHA",
   "venue": "费城",
   "result": "H",
   "score": "2-1"
  },
  {
   "id": 69,
   "stage": "group",
   "group": "K",
   "date": "2026-06-28",
   "t": "07:30",
   "home": "COL",
   "away": "POR",
   "venue": "迈阿密",
   "result": "D",
   "score": "0-0"
  },
  {
   "id": 70,
   "stage": "group",
   "group": "K",
   "date": "2026-06-28",
   "t": "07:30",
   "home": "COD",
   "away": "UZB",
   "venue": "亚特兰大",
   "result": "H",
   "score": "3-1"
  },
  {
   "id": 71,
   "stage": "group",
   "group": "J",
   "date": "2026-06-28",
   "t": "10:00",
   "home": "ALG",
   "away": "AUT",
   "venue": "堪萨斯城",
   "result": "D",
   "score": "3-3"
  },
  {
   "id": 72,
   "stage": "group",
   "group": "J",
   "date": "2026-06-28",
   "t": "10:00",
   "home": "JOR",
   "away": "ARG",
   "venue": "达拉斯",
   "result": "A",
   "score": "1-3"
  },
  {
   "id": 73,
   "stage": "r32",
   "group": null,
   "date": "2026-06-29",
   "t": "03:00",
   "home": "RSA",
   "away": "CAN",
   "venue": "待定",
   "result": "A",
   "score": "0-1",
   "espnId": "760486"
  },
  {
   "id": 74,
   "stage": "r32",
   "group": null,
   "date": "2026-06-30",
   "t": "01:00",
   "home": "BRA",
   "away": "JPN",
   "venue": "待定",
   "result": "H",
   "score": "2-1",
   "espnId": "760487"
  },
  {
   "id": 75,
   "stage": "r32",
   "group": null,
   "date": "2026-06-30",
   "t": "04:30",
   "home": "GER",
   "away": "PAR",
   "venue": "待定",
   "result": "D",
   "score": "1-1 (点球3-4)",
   "espnId": "760489"
  },
  {
   "id": 76,
   "stage": "r32",
   "group": null,
   "date": "2026-06-30",
   "t": "09:00",
   "home": "NED",
   "away": "MAR",
   "venue": "蒙特雷",
   "result": "D",
   "score": "1-1 (点球2-3)",
   "espnId": "760488"
  },
  {
   "id": 77,
   "stage": "r32",
   "group": null,
   "date": "2026-07-01",
   "t": "01:00",
   "home": "CIV",
   "away": "NOR",
   "venue": "待定",
   "result": "A",
   "score": "1-2",
   "espnId": "760490"
  },
  {
   "id": 78,
   "stage": "r32",
   "group": null,
   "date": "2026-07-01",
   "t": "05:00",
   "home": "FRA",
   "away": "SWE",
   "venue": "待定",
   "result": "H",
   "score": "3-0",
   "espnId": "760492"
  },
  {
   "id": 79,
   "stage": "r32",
   "group": null,
   "date": "2026-07-01",
   "t": "10:00",
   "home": "MEX",
   "away": "ECU",
   "venue": "墨西哥城",
   "result": "H",
   "score": "2-0",
   "espnId": "760491"
  },
  {
   "id": 80,
   "stage": "r32",
   "group": null,
   "date": "2026-07-02",
   "t": "00:00",
   "home": "ENG",
   "away": "COD",
   "venue": "待定",
   "result": "H",
   "score": "2-1",
   "espnId": "760495"
  },
  {
   "id": 81,
   "stage": "r32",
   "group": null,
   "date": "2026-07-02",
   "t": "04:00",
   "home": "BEL",
   "away": "SEN",
   "venue": "待定",
   "result": "H",
   "score": "3-2",
   "espnId": "760493"
  },
  {
   "id": 82,
   "stage": "r32",
   "group": null,
   "date": "2026-07-02",
   "t": "08:00",
   "home": "USA",
   "away": null,
   "venue": "待定",
   "result": null,
   "score": null,
   "espnId": "760494"
  },
  {
   "id": 83,
   "stage": "r32",
   "group": null,
   "date": "2026-07-03",
   "t": "03:00",
   "home": "ESP",
   "away": "AUT",
   "venue": "待定",
   "result": "H",
   "score": "3-0",
   "espnId": "760497"
  },
  {
   "id": 84,
   "stage": "r32",
   "group": null,
   "date": "2026-07-03",
   "t": "07:00",
   "home": "POR",
   "away": "CRO",
   "venue": "多伦多",
   "result": "H",
   "score": "2-1",
   "espnId": "760496"
  },
  {
   "id": 85,
   "stage": "r32",
   "group": null,
   "date": "2026-07-03",
   "t": "11:00",
   "home": "SUI",
   "away": "ALG",
   "venue": "温哥华",
   "result": "H",
   "score": "2-0",
   "espnId": "760498"
  },
  {
   "id": 86,
   "stage": "r32",
   "group": null,
   "date": "2026-07-04",
   "t": "02:00",
   "home": "AUS",
   "away": "EGY",
   "venue": "待定",
   "result": "D",
   "score": "1-1 (点球2-4)",
   "espnId": "760499"
  },
  {
   "id": 87,
   "stage": "r32",
   "group": null,
   "date": "2026-07-04",
   "t": "06:00",
   "home": "ARG",
   "away": "CPV",
   "venue": "待定",
   "result": "H",
   "score": "3-2",
   "espnId": "760500"
  },
  {
   "id": 88,
   "stage": "r32",
   "group": null,
   "date": "2026-07-04",
   "t": "09:30",
   "home": "COL",
   "away": "GHA",
   "venue": "待定",
   "result": "H",
   "score": "1-0",
   "espnId": "760501"
  },
  {
   "id": 89,
   "stage": "r16",
   "group": null,
   "date": "2026-07-05",
   "t": "01:00",
   "home": "CAN",
   "away": "MAR",
   "venue": "待定",
   "result": "A",
   "score": "0-3",
   "espnId": "760502"
  },
  {
   "id": 90,
   "stage": "r16",
   "group": null,
   "date": "2026-07-05",
   "t": "05:00",
   "home": "PAR",
   "away": "FRA",
   "venue": "待定",
   "result": "A",
   "score": "0-1",
   "espnId": "760503"
  },
  {
   "id": 91,
   "stage": "r16",
   "group": null,
   "date": "2026-07-06",
   "t": "04:00",
   "home": "BRA",
   "away": "NOR",
   "venue": "待定",
   "result": "A",
   "score": "1-2",
   "espnId": "760504"
  },
  {
   "id": 92,
   "stage": "r16",
   "group": null,
   "date": "2026-07-06",
   "t": "09:00",
   "home": "MEX",
   "away": "ENG",
   "venue": "墨西哥城",
   "result": "A",
   "score": "2-3",
   "espnId": "760505"
  },
  {
   "id": 93,
   "stage": "r16",
   "group": null,
   "date": "2026-07-07",
   "t": "03:00",
   "home": "POR",
   "away": "ESP",
   "venue": "待定",
   "result": "A",
   "score": "0-1",
   "espnId": "760506"
  },
  {
   "id": 94,
   "stage": "r16",
   "group": null,
   "date": "2026-07-07",
   "t": "08:00",
   "home": "USA",
   "away": "BEL",
   "venue": "待定",
   "result": "A",
   "score": "1-4",
   "espnId": "760507"
  },
  {
   "id": 95,
   "stage": "r16",
   "group": null,
   "date": "2026-07-08",
   "t": "00:00",
   "home": "ARG",
   "away": "EGY",
   "venue": "待定",
   "result": "H",
   "score": "3-2",
   "espnId": "760509"
  },
  {
   "id": 96,
   "stage": "r16",
   "group": null,
   "date": "2026-07-08",
   "t": "04:00",
   "home": "SUI",
   "away": "COL",
   "venue": "温哥华",
   "result": null,
   "score": null,
   "espnId": "760508"
  },
  {
   "id": 97,
   "stage": "qf",
   "group": null,
   "date": "2026-07-10",
   "t": null,
   "home": null,
   "away": null,
   "venue": "待定",
   "result": null,
   "score": null
  },
  {
   "id": 98,
   "stage": "qf",
   "group": null,
   "date": "2026-07-10",
   "t": null,
   "home": null,
   "away": null,
   "venue": "待定",
   "result": null,
   "score": null
  },
  {
   "id": 99,
   "stage": "qf",
   "group": null,
   "date": "2026-07-11",
   "t": null,
   "home": null,
   "away": null,
   "venue": "待定",
   "result": null,
   "score": null
  },
  {
   "id": 100,
   "stage": "qf",
   "group": null,
   "date": "2026-07-12",
   "t": null,
   "home": null,
   "away": null,
   "venue": "待定",
   "result": null,
   "score": null
  },
  {
   "id": 101,
   "stage": "sf",
   "group": null,
   "date": "2026-07-15",
   "t": null,
   "home": null,
   "away": null,
   "venue": "待定",
   "result": null,
   "score": null
  },
  {
   "id": 102,
   "stage": "sf",
   "group": null,
   "date": "2026-07-16",
   "t": null,
   "home": null,
   "away": null,
   "venue": "待定",
   "result": null,
   "score": null
  },
  {
   "id": 103,
   "stage": "third",
   "group": null,
   "date": "2026-07-19",
   "t": null,
   "home": null,
   "away": null,
   "venue": "迈阿密",
   "result": null,
   "score": null
  },
  {
   "id": 104,
   "stage": "final",
   "group": null,
   "date": "2026-07-20",
   "t": null,
   "home": null,
   "away": null,
   "venue": "纽约/新泽西",
   "result": null,
   "score": null
  }
 ]
};
